name: Technomatic
url: http://technomatic.be
description: A compsci blog by Kris Bellemans

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
